apiVersion: v1
kind: Service
metadata:
  name: orthanc
  namespace: orthanc
  labels:
    app.kubernetes.io/name: orthanc
spec:
  selector:
    module: orthanc
  type: LoadBalancer
  ports:
    - name: http
      port: 8042
      targetPort: 8042
      protocol: TCP
    - name: https
      port: 4242
      targetPort: 4242
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: orthanc
  namespace: orthanc
spec:  
  replicas: 1
  selector:
    matchLabels:
      module: orthanc
  template:
    metadata:
      labels:
        # This label is used as a selector in Service definition
        module: orthanc
    spec:
      #volumes:
      #- name: orthanc-pvc
      #  persistentVolumeClaim:
      #    claimName: orthanc-pvc
      containers:
      - name: orthanc
        image: jodogne/orthanc
        ports:
        - name: http
          containerPort: 8042
        - name: https
          containerPort: 4242
        #volumeMounts:
        #- mountPath: /var/lib/orthanc/db/
        #  name: orthanc-pvc